# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.1.3

steps:

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: ./phpunit
  displayName: 'Run tests with phpunit'